a = input("Digite algo:")
print("O tipo primitivo desse valor é {}: ".format(type(a)))
print("Só tem espaços {}?".format(a.isspace()))
print("É um número {}?".format(a.isnumeric()))
print("É alfabético {}?".format(a.isalpha()))
print("É alfanumerico {}?".format(a.isalnum()))
print("Está em maiusculo {}?".format(a.isupper()))
print("Está em minusculo {}?".format(a.islower()))
print("Está capitalizada {}?".format(a.istitle()))
